# Generated by Django 3.2.5 on 2022-09-21 01:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('experiment_version', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(auto_now=True)),
                ('unique_code', models.CharField(blank=True, max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.participant')),
            ],
        ),
        migrations.CreateModel(
            name='ReportRecord',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(auto_now=True)),
                ('article_id', models.IntegerField()),
                ('condition_id', models.IntegerField()),
                ('input_veracity', models.CharField(max_length=50)),
                ('input_q', models.IntegerField()),
                ('input_r1', models.IntegerField()),
                ('input_r2', models.IntegerField()),
                ('input_r3', models.IntegerField()),
                ('study_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.studyrecord')),
            ],
        ),
    ]
