# Generated by Django 3.2.5 on 2022-09-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrecord',
            name='article_order',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='studyrecord',
            name='condition_order',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
