# Generated by Django 3.2.5 on 2022-09-21 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0002_auto_20220921_0248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyrecord',
            old_name='user',
            new_name='participant',
        ),
    ]
