# Generated by Django 3.2.5 on 2022-09-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0003_rename_user_studyrecord_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrecord',
            name='input_q',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='reportrecord',
            name='input_r1',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='reportrecord',
            name='input_r2',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='reportrecord',
            name='input_r3',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='reportrecord',
            name='input_veracity',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
