# Generated by Django 3.2.5 on 2022-09-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0004_auto_20220921_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrecord',
            name='input_q',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='reportrecord',
            name='input_r1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='reportrecord',
            name='input_r2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='reportrecord',
            name='input_r3',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
