# Generated by Django 3.2.5 on 2022-10-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0006_studyrecord_questionnaire_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportrecord',
            name='input_q',
        ),
        migrations.AddField(
            model_name='reportrecord',
            name='input_q1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reportrecord',
            name='input_q2',
            field=models.CharField(blank=True, max_length=2018),
        ),
        migrations.AlterField(
            model_name='reportrecord',
            name='input_r1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reportrecord',
            name='input_r2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reportrecord',
            name='input_r3',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
