# Generated by Django 3.2.5 on 2022-10-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0008_studyrecord_demographic_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrecord',
            name='user_logs',
            field=models.TextField(blank=True),
        ),
    ]
